# Generated by Django 3.1.7 on 2021-03-16 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('nutriscore', models.CharField(max_length=1, null=True, verbose_name='Nutriscore')),
                ('brand', models.CharField(max_length=100, null=True, verbose_name='Marque')),
                ('url_opff', models.URLField(null=True, verbose_name='Lien Openfoodfact')),
                ('ingredients', models.TextField(null=True, verbose_name='Ingredients du produit')),
                ('image', models.URLField(null=True)),
                ('opff_id', models.BigIntegerField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pure_beurre.category')),
            ],
        ),
    ]
