LIST_CATEGORIES = [
    "Snacks",
    "Viandes",
    "Fromages",
    "Charcuteries",
    "Fruits",
    "Poissons",
    "Légumes",
    "Biscuits",
    "Boissons aux fruits",
    "Chocolats",
    "Pains",
    "Yaourts",
    "Fruits à coques et dérives",
    "Jus de fruits",
    "Huiles",
    "Vins",
    "Légumineuses",
    "Fruits",
    "Pâtisseries",
    "Viennoiseries",
    "Cereales pour petit-dejeuner"
    "Glaces et sorbets",
    "Bieres",
    "Cafés",
    "Laits",
    "Sodas",
    "Pâtes à tartiner",
    "Sauces"
]
